<a href="https://colab.research.google.com/github/faneza31nur/Natural-Language-Processing-NLP-/blob/main/LK_Faneza_Nur_Mardania_T2_Labeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Data Analis Angkatan 2 Tahun 2026_Faneza Nur Mardania/21 Agustus 2026_Pertemuan 26/File Tugas/scraped_playstore2.csv')   # ganti dengan file Anda
print('Dimensi data:', df.shape)
df.head()

Dimensi data: (5000, 4)

,id,teks,tanggal,sumber
0,e113ae49-d462-4dd3-baa1-429a1905f41c,"woi cs bales komplain gw di alfagift, pesenan ...",2026-08-20 07:00:54,playstore
1,8781d527-5694-4fea-8ed2-dba49940755b,bagus tapi sekarang poin kecil dan kupon ngaco...,2026-08-20 06:49:02,playstore
2,d5676f3e-d0f8-4dca-a972-3882edc941fb,harga jauh lebih mahal dari toko sebelah,2026-08-20 04:18:08,playstore
3,4e7be2a7-1fdf-4925-ad10-00d51d77f726,"lambat bagaikan siput pengantaran kurirnya, ra...",2026-08-20 03:02:15,playstore
4,7c04ce40-53e6-4855-a792-ed15ca533912,mantap,2026-08-20 00:03:46,playstore

# kamus kata positif dan negatif Bahasa Indonesia

In [ ]:
positif = [
    'bagus', 'baguss', 'bagus banget', 'bagus bgt', 'bagus sekali', 'sangat bagus',
                'mantap', 'mantapp', 'mantul', 'keren', 'kereen', 'keren banget', 'hebat',
                'luar biasa', 'terbaik', 'top', 'oke', 'ok', 'suka', 'sukaa', 'suka banget',
                'sangat suka', 'senang', 'seneng', 'puas', 'puas banget', 'memuaskan', 'baik',
                'baik sekali', 'membantu', 'sangat membantu', 'membatu', 'bermanfaat', 'berguna',
                'memudahkan', 'mudah', 'praktis', 'simple', 'nyaman', 'lancar', 'cepat',
                'responsif', 'lengkap', 'harga murah', 'lebih murah', 'hemat', 'menguntungkan',
                'promo bagus', 'promo menarik', 'promo banyak', 'voucher bagus', 'voucher menarik',
                'diskon bagus', 'diskon besar', 'gratis ongkir', 'ongkir gratis', 'pengiriman cepat',
                'cepat sampai', 'pesanan cepat sampai', 'kurir ramah', 'pelayanan bagus',
                'pelayanan baik', 'layanan bagus', 'layanan baik', 'stok lengkap',
                'barang lengkap', 'produk lengkap', 'aplikasi bagus', 'aplikasi sangat membantu',
                'recommended', 'rekomendasi', 'worth it', 'good', 'great', 'nice',
                'terima kasih', 'terimakasih', 'makasih', 'makasi'
]

negatif = [
    'jelek', 'jelek banget', 'jelek bgt', 'sangat jelek', 'buruk', 'buruk banget',
                'parah', 'parah banget', 'kecewa', 'kecewa banget', 'mengecewakan',
                'tidak memuaskan', 'kurang memuaskan', 'benci', 'kesal', 'kesel', 'sebel',
                'jengkel', 'marah', 'rugi', 'merugikan', 'percuma', 'payah', 'sampah',
                'tolol', 'bodoh', 'error', 'eror', 'sering error', 'error terus',
                'bermasalah', 'banyak masalah', 'bug', 'ngebug', 'lemot', 'lemot banget',
                'lambat', 'lambat banget', 'loading lama', 'loading terus', 'loading tidak selesai',
                'hang', 'stuck', 'crash', 'keluar sendiri', 'keluar aplikasi', 'kelempar keluar',
                'tidak bisa', 'gabisa', 'ga bisa', 'gak bisa', 'nggak bisa', 'gk bisa',
                'gagal', 'gagal terus', 'tidak berhasil', 'tidak berfungsi', 'tidak jalan',
                'tidak dapat diakses', 'tidak bisa diakses', 'gabisa diakses',
                'tidak bisa login', 'gabisa login', 'gagal login', 'susah login',
                'refund lama', 'refund lambat', 'refund belum masuk', 'uang belum kembali',
                'uang belum masuk', 'refund tidak masuk', 'belum dikembalikan',
                'stok habis', 'stockout', 'stok tidak sesuai', 'stok tidak tersedia',
                'stok tidak update', 'stok kosong', 'barang kosong', 'produk kosong',
                'pesanan dibatalkan', 'pesanan batal', 'dibatalin', 'dibatalkan sepihak',
                'pengiriman lama', 'pengiriman lambat', 'belum dikirim', 'tidak dikirim',
                'kurir lama', 'kurir tidak datang', 'kurir tidak mengantar', 'kurir malas',
                'kurir tidak mau', 'pesanan terlambat', 'telat', 'terlambat',
                'voucher tidak bisa', 'voucher tidak dapat digunakan', 'voucher gagal',
                'promo tidak bisa digunakan', 'diskon tidak berlaku',
                'ongkir mahal', 'kena ongkir', 'ada ongkir', 'gratis ongkir hilang',
                'alamat tidak bisa', 'alamat tidak tercover', 'alamat tidak tersedia',
                'susah tambah alamat', 'tidak bisa tambah alamat',
                'barang tidak ada', 'barang tidak sesuai', 'barang kurang',
                'pesanan salah', 'harga tidak sesuai', 'mahal', 'kemahalan',
                'uninstall', 'hapus aplikasi', 'tidak worth it', 'ga worth it',
                'gak worth it', 'sangat tidak worth it', 'tolong perbaiki',
                'minta diperbaiki', 'mohon diperbaiki'
]

print('Jumlah kata positif:', len(positif))
print('Jumlah kata negatif:', len(negatif))

Jumlah kata positif: 79
Jumlah kata negatif: 126

# Fungsi auto-labeling berdasarkan jumlah kata positif/negatif

In [ ]:
def auto_label(teks):
    if not isinstance(teks, str):
        return 'netral'
    t = teks.lower()
    skor_pos = sum(1 for k in positif if k in t)
    skor_neg = sum(1 for k in negatif if k in t)

    if skor_pos > skor_neg:
        return 'positif'
    elif skor_neg > skor_pos:
        return 'negatif'
    else:
        return 'netral'

df['sentimen_auto'] = df['teks'].apply(auto_label)
print(df['sentimen_auto'].value_counts())
df.head(10)

sentimen_auto
positif    2023
netral     1575
negatif    1402
Name: count, dtype: int64

,id,teks,tanggal,sumber,sentimen_auto
0,e113ae49-d462-4dd3-baa1-429a1905f41c,"woi cs bales komplain gw di alfagift, pesenan ...",2026-08-20 07:00:54,playstore,netral
1,8781d527-5694-4fea-8ed2-dba49940755b,bagus tapi sekarang poin kecil dan kupon ngaco...,2026-08-20 06:49:02,playstore,positif
2,d5676f3e-d0f8-4dca-a972-3882edc941fb,harga jauh lebih mahal dari toko sebelah,2026-08-20 04:18:08,playstore,negatif
3,4e7be2a7-1fdf-4925-ad10-00d51d77f726,"lambat bagaikan siput pengantaran kurirnya, ra...",2026-08-20 03:02:15,playstore,negatif
4,7c04ce40-53e6-4855-a792-ed15ca533912,mantap,2026-08-20 00:03:46,playstore,positif
5,f1c42818-d4b2-4a56-8969-2a6199605f7e,"pengembalian dana nya buruk, dana tidak pernah...",2026-08-19 22:41:44,playstore,negatif
6,23013a5d-3a1d-4b57-b9c2-302db73945d4,Apk Scan nih ( penipuan) masa katanya bisa bel...,2026-08-19 13:43:56,playstore,netral
7,eb16f96c-d2e3-437b-968b-2e357050c86e,maaf saya kasih 1 biar di notice. tolong buat ...,2026-08-19 13:40:07,playstore,netral
8,663f7e36-5ff6-473b-8dbc-5b781818880b,"transaksi pick up pada 17 Agustus 2026, dan su...",2026-08-19 13:33:50,playstore,positif
9,43211bf4-31b6-4ec3-87f6-a1d37a86292e,"jujur padahal alfanya deket, cmn aku tetep pak...",2026-08-19 12:50:25,playstore,positif

#  KOREKSI MANUAL pada minimal 50 baris pertama.
Ini penting karena lexicon sering salah pada kalimat sarkastik atau bercampur

In [ ]:
# Pisahkan baris untuk dikoreksi manual
sample = df.head(50).copy()

# Cara 1: simpan ke CSV, edit di Excel, lalu muat ulang
sample.to_csv('untuk_koreksi_manual.csv', index=False)

In [ ]:
# # Setelah dikoreksi di Excel/Sheets, simpan kembali sebagai 'sudah_dikoreksi.csv' lalu muat:
koreksi = pd.read_csv('/content/drive/MyDrive/Data Analis Angkatan 2 Tahun 2026_Faneza Nur Mardania/21 Agustus 2026_Pertemuan 26/File Tugas/setelah_dikoreksi.csv', sep=';')

In [ ]:
# Cara 2: koreksi inline di notebook (untuk demo)
# sample.loc[2, 'sentimen_auto'] = 'positif'   # contoh
# sample.loc[0, 'sentimen_auto'] = 'negatif'
# sample.loc[1, 'sentimen_auto'] = 'netral'

#  Gabungkan kembali dengan sisa data dan simpan dataset final berlabel

In [ ]:
# Asumsikan koreksi sudah dimasukkan ke sample['sentimen_auto']

# Re-load koreksi DataFrame correctly, assuming it's comma-separated
koreksi_path = '/content/drive/MyDrive/Data Analis Angkatan 2 Tahun 2026_Faneza Nur Mardania/21 Agustus 2026_Pertemuan 26/File Tugas/setelah_dikoreksi.csv'
koreksi = pd.read_csv(koreksi_path)

df.loc[:49, 'sentimen_auto'] = koreksi['sentimen_auto'].values
df = df.rename(columns={'sentimen_auto': 'sentimen'})

# Buang baris netral jika ingin klasifikasi 2 kelas saja
df_2kelas = df[df['sentimen'].isin(['positif', 'negatif', 'netral'])].reset_index(drop=True)
df_2kelas.to_csv('data_labeled.csv', index=False)

print('Distribusi sentimen final:')
print(df_2kelas['sentimen'].value_counts())

Distribusi sentimen final:
sentimen
positif    2017
netral     1565
negatif    1418
Name: count, dtype: int64